export const defaults = {
  baseUrl: "https://www.ansin-anzen.jp",
  loginPath: "/admin/auth/login",
  authPath: "/admin/auth/auth",
  checkPath: "/admin/absentlate-members/list",
  groupId: "6077",
  perPage: "1",
  timeZone: "Asia/Tokyo",
  windowStart: "07:30",
  windowEnd: "09:00",
  publishStart: "07:30",
  publishEnd: "09:10",
  outsideCheckMinute: 0,
  outsideRetryIntervalMinutes: 10,
  outsideRetryAttempts: 3,
  requestTimeoutMs: 20000,
  historyLimit: 240,
  publicHistoryLimit: 120,
  logsDir: "logs",
  docsDir: "docs",
  gitPush: false
};
